version: "3.9"
services:
  web:
    build:
      context: .
      target: dev
    image: schema-registry:last
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./.local/sqlite:/tmp/sqlite
    restart: on-failure
    environment:
      DEBUG: 1
      SECRET_KEY: django-insecure-873=x2#_fm0gl*wsxbgvmdnhqphcf6!-+594e*2w*_^-16d=
      DATABASE_URL: sqlite:////tmp/sqlite/schema-registry.db
      GS_BUCKET_NAME: schema-registry-static
      ALLAUTH_GITLAB_URL: https://gitlab.shiftwitherin.com
      GOOGLE_APPLICATION_CREDENTIALS: .local/service-account.json
