# Generated by Django 4.0 on 2021-12-07 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=64, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'schema',
                'verbose_name_plural': 'schemas',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='number', editable=False)),
                ('data', models.JSONField(default=dict, verbose_name='data')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', related_query_name='version', to='schema_registry.schema', verbose_name='schema')),
            ],
            options={
                'verbose_name': 'version',
                'verbose_name_plural': 'versions',
                'unique_together': {('schema', 'number')},
            },
        ),
    ]
